/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EventsRouteImport } from './routes/events'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as AuthorsSlugRouteImport } from './routes/authors.$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardEditionsRouteImport } from './routes/dashboard/editions'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardTeamRouteImport } from './routes/dashboard/team'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as DashboardArticlesIndexRouteImport } from './routes/dashboard/articles/index'
import { Route as DashboardArticlesArticleIdRouteImport } from './routes/dashboard/articles/$articleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsSlugRoute = AuthorsSlugRouteImport.update({
  id: '/authors/$slug',
  path: '/authors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEditionsRoute = DashboardEditionsRouteImport.update({
  id: '/editions',
  path: '/editions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgramsRoute,
} as any)
const DashboardArticlesIndexRoute = DashboardArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardArticlesArticleIdRoute =
  DashboardArticlesArticleIdRouteImport.update({
    id: '/articles/$articleId',
    path: '/articles/$articleId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/dashboard/editions': typeof DashboardEditionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/events/$slug': typeof EventsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/articles/$articleId': typeof DashboardArticlesArticleIdRoute
  '/dashboard/articles/': typeof DashboardArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRouteWithChildren
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/dashboard/editions': typeof DashboardEditionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/events/$slug': typeof EventsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/articles/$articleId': typeof DashboardArticlesArticleIdRoute
  '/dashboard/articles': typeof DashboardArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/dashboard/editions': typeof DashboardEditionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/events/$slug': typeof EventsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/articles/$articleId': typeof DashboardArticlesArticleIdRoute
  '/dashboard/articles/': typeof DashboardArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/events'
    | '/news'
    | '/privacy'
    | '/programs'
    | '/subscribe'
    | '/terms'
    | '/article/$slug'
    | '/authors/$slug'
    | '/dashboard/editions'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/events/$slug'
    | '/programs/$slug'
    | '/dashboard/'
    | '/dashboard/articles/$articleId'
    | '/dashboard/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/events'
    | '/news'
    | '/privacy'
    | '/programs'
    | '/subscribe'
    | '/terms'
    | '/article/$slug'
    | '/authors/$slug'
    | '/dashboard/editions'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/events/$slug'
    | '/programs/$slug'
    | '/dashboard'
    | '/dashboard/articles/$articleId'
    | '/dashboard/articles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/events'
    | '/news'
    | '/privacy'
    | '/programs'
    | '/subscribe'
    | '/terms'
    | '/article/$slug'
    | '/authors/$slug'
    | '/dashboard/editions'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/events/$slug'
    | '/programs/$slug'
    | '/dashboard/'
    | '/dashboard/articles/$articleId'
    | '/dashboard/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EventsRoute: typeof EventsRouteWithChildren
  NewsRoute: typeof NewsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  SubscribeRoute: typeof SubscribeRoute
  TermsRoute: typeof TermsRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  AuthorsSlugRoute: typeof AuthorsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$slug': {
      id: '/authors/$slug'
      path: '/authors/$slug'
      fullPath: '/authors/$slug'
      preLoaderRoute: typeof AuthorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/editions': {
      id: '/dashboard/editions'
      path: '/editions'
      fullPath: '/dashboard/editions'
      preLoaderRoute: typeof DashboardEditionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/dashboard/articles/': {
      id: '/dashboard/articles/'
      path: '/articles'
      fullPath: '/dashboard/articles/'
      preLoaderRoute: typeof DashboardArticlesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/articles/$articleId': {
      id: '/dashboard/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/dashboard/articles/$articleId'
      preLoaderRoute: typeof DashboardArticlesArticleIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardEditionsRoute: typeof DashboardEditionsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardArticlesArticleIdRoute: typeof DashboardArticlesArticleIdRoute
  DashboardArticlesIndexRoute: typeof DashboardArticlesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEditionsRoute: DashboardEditionsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardArticlesArticleIdRoute: DashboardArticlesArticleIdRoute,
  DashboardArticlesIndexRoute: DashboardArticlesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface ProgramsRouteChildren {
  ProgramsSlugRoute: typeof ProgramsSlugRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsSlugRoute: ProgramsSlugRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EventsRoute: EventsRouteWithChildren,
  NewsRoute: NewsRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  SubscribeRoute: SubscribeRoute,
  TermsRoute: TermsRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  AuthorsSlugRoute: AuthorsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
